export const CONSTANTS = {
  AUTO_SAVE: { DELAY_MS: 2000 },
  CONVERSATION: { TITLE_MAX_LENGTH: 50, TITLE_TRUNCATE_LENGTH: 47 },
  FILES: { BATCH_CHANGE_THRESHOLD: 10 },
  MESSAGES: { MAX_COUNT: 1000 },
} as const;
