export const CONSTANTS = {
  AUTO_SAVE: { DELAY_MS: 2000 },
  CONVERSATION: { TITLE_MAX_LENGTH: 50, TITLE_TRUNCATE_LENGTH: 47 },
  FILES: { BATCH_CHANGE_THRESHOLD: 10 },
  MESSAGES: { MAX_COUNT: 1000 },
  UI: {
    TEXTAREA_MAX_HEIGHT: 200, // pixels
    FILE_WATCHER_DEBOUNCE_MS: 300,
  },
  TIME: {
    MILLISECONDS_PER_SECOND: 1000,
    SECONDS_PER_MINUTE: 60,
    MINUTES_PER_HOUR: 60,
    HOURS_PER_DAY: 24,
    DAYS_PER_WEEK: 7,
  },
} as const;

// Computed time constants for convenience
export const TIME_MS = {
  ONE_SECOND: CONSTANTS.TIME.MILLISECONDS_PER_SECOND,
  ONE_MINUTE: CONSTANTS.TIME.SECONDS_PER_MINUTE * CONSTANTS.TIME.MILLISECONDS_PER_SECOND,
  ONE_HOUR: CONSTANTS.TIME.MINUTES_PER_HOUR * CONSTANTS.TIME.SECONDS_PER_MINUTE * CONSTANTS.TIME.MILLISECONDS_PER_SECOND,
  ONE_DAY: CONSTANTS.TIME.HOURS_PER_DAY * CONSTANTS.TIME.MINUTES_PER_HOUR * CONSTANTS.TIME.SECONDS_PER_MINUTE * CONSTANTS.TIME.MILLISECONDS_PER_SECOND,
  ONE_WEEK: CONSTANTS.TIME.DAYS_PER_WEEK * CONSTANTS.TIME.HOURS_PER_DAY * CONSTANTS.TIME.MINUTES_PER_HOUR * CONSTANTS.TIME.SECONDS_PER_MINUTE * CONSTANTS.TIME.MILLISECONDS_PER_SECOND,
} as const;
